export interface Question {
  id: number;
  text: string;
  category: string;
  options: string[];
  correctAnswer: string;
}

export const ASSESSMENT_QUESTIONS: Question[] = [
  // Logical Reasoning (30 questions)
  { id: 1, text: "If all roses are flowers and some flowers fade quickly, which statement must be true?", category: "Logical Reasoning", options: ["All roses fade quickly", "Some roses fade quickly", "No roses fade quickly", "All flowers are roses"], correctAnswer: "Some roses fade quickly" },
  { id: 2, text: "Complete the sequence: 2, 6, 12, 20, 30, ?", category: "Logical Reasoning", options: ["40", "42", "44", "46"], correctAnswer: "42" },
  { id: 3, text: "If A is taller than B, and B is taller than C, who is the shortest?", category: "Logical Reasoning", options: ["A", "B", "C", "Cannot determine"], correctAnswer: "C" },
  { id: 4, text: "What comes next in the pattern: O, T, T, F, F, S, S, ?", category: "Logical Reasoning", options: ["E", "N", "T", "F"], correctAnswer: "E" },
  { id: 5, text: "If it takes 5 machines 5 minutes to make 5 widgets, how long would it take 100 machines to make 100 widgets?", category: "Logical Reasoning", options: ["5 minutes", "20 minutes", "100 minutes", "500 minutes"], correctAnswer: "5 minutes" },
  { id: 6, text: "Which word does not belong: Apple, Orange, Carrot, Banana?", category: "Logical Reasoning", options: ["Apple", "Orange", "Carrot", "Banana"], correctAnswer: "Carrot" },
  { id: 7, text: "If some cats are dogs and all dogs are animals, which must be true?", category: "Logical Reasoning", options: ["All cats are animals", "Some cats are animals", "No cats are animals", "All animals are cats"], correctAnswer: "Some cats are animals" },
  { id: 8, text: "What is the next number: 1, 1, 2, 3, 5, 8, ?", category: "Logical Reasoning", options: ["11", "13", "15", "16"], correctAnswer: "13" },
  { id: 9, text: "If today is Monday, what day will it be 100 days from now?", category: "Logical Reasoning", options: ["Monday", "Tuesday", "Wednesday", "Thursday"], correctAnswer: "Wednesday" },
  { id: 10, text: "Which shape completes the pattern: Circle, Square, Triangle, Circle, Square, ?", category: "Logical Reasoning", options: ["Circle", "Square", "Triangle", "Pentagon"], correctAnswer: "Triangle" },
  { id: 11, text: "If all birds can fly and penguins are birds, what can we conclude?", category: "Logical Reasoning", options: ["The premise is flawed", "Penguins can fly", "All flying things are birds", "Birds are penguins"], correctAnswer: "The premise is flawed" },
  { id: 12, text: "Complete: 3, 9, 27, 81, ?", category: "Logical Reasoning", options: ["162", "243", "324", "405"], correctAnswer: "243" },
  { id: 13, text: "If A = 1, B = 2, C = 3, what does CAB equal?", category: "Logical Reasoning", options: ["312", "123", "321", "213"], correctAnswer: "312" },
  { id: 14, text: "Which is the odd one out: 2, 4, 6, 9, 10?", category: "Logical Reasoning", options: ["2", "4", "9", "10"], correctAnswer: "9" },
  { id: 15, text: "If you rearrange the letters 'CIFAIPC' you would have the name of a(n):", category: "Logical Reasoning", options: ["City", "Animal", "Ocean", "Country"], correctAnswer: "Ocean" },
  { id: 16, text: "What is the missing number: 2, 5, 10, 17, 26, ?", category: "Logical Reasoning", options: ["35", "37", "39", "41"], correctAnswer: "37" },
  { id: 17, text: "If some teachers are doctors and all doctors are educated, what must be true?", category: "Logical Reasoning", options: ["All teachers are educated", "Some teachers are educated", "No teachers are educated", "All educated people are teachers"], correctAnswer: "Some teachers are educated" },
  { id: 18, text: "Which number should replace the question mark: 4, 9, 16, 25, ?", category: "Logical Reasoning", options: ["30", "32", "36", "40"], correctAnswer: "36" },
  { id: 19, text: "If BOOK is coded as CPPL, how is PAGE coded?", category: "Logical Reasoning", options: ["QBHF", "QBGF", "OBHF", "QCHF"], correctAnswer: "QBHF" },
  { id: 20, text: "What comes next: J, F, M, A, M, ?", category: "Logical Reasoning", options: ["J", "A", "S", "N"], correctAnswer: "J" },
  { id: 21, text: "If 3 cats catch 3 mice in 3 minutes, how many cats are needed to catch 100 mice in 100 minutes?", category: "Logical Reasoning", options: ["1", "3", "33", "100"], correctAnswer: "3" },
  { id: 22, text: "Which word is the opposite of 'abundant'?", category: "Logical Reasoning", options: ["Scarce", "Plenty", "Rich", "Full"], correctAnswer: "Scarce" },
  { id: 23, text: "Complete the analogy: Hand is to Glove as Foot is to ?", category: "Logical Reasoning", options: ["Shoe", "Sock", "Boot", "Sandal"], correctAnswer: "Shoe" },
  { id: 24, text: "If all squares are rectangles and some rectangles are rhombuses, which must be true?", category: "Logical Reasoning", options: ["All squares are rhombuses", "Some squares might be rhombuses", "No squares are rhombuses", "All rhombuses are squares"], correctAnswer: "Some squares might be rhombuses" },
  { id: 25, text: "What is the next letter: A, C, F, J, O, ?", category: "Logical Reasoning", options: ["S", "T", "U", "V"], correctAnswer: "U" },
  { id: 26, text: "If TRAIN is written as 27195, how is BRAIN written?", category: "Logical Reasoning", options: ["27195", "12195", "29185", "21985"], correctAnswer: "12195" },
  { id: 27, text: "Which number doesn't fit: 1, 4, 9, 16, 20, 25?", category: "Logical Reasoning", options: ["1", "9", "20", "25"], correctAnswer: "20" },
  { id: 28, text: "If you have 3 apples and you take away 2, how many do you have?", category: "Logical Reasoning", options: ["1", "2", "3", "5"], correctAnswer: "2" },
  { id: 29, text: "Complete: 1, 4, 9, 16, 25, 36, ?", category: "Logical Reasoning", options: ["42", "45", "49", "54"], correctAnswer: "49" },
  { id: 30, text: "If all athletes are fit and some fit people are vegetarians, which could be true?", category: "Logical Reasoning", options: ["All athletes are vegetarians", "Some athletes are vegetarians", "No athletes are vegetarians", "All vegetarians are athletes"], correctAnswer: "Some athletes are vegetarians" },

  // Verbal Ability (30 questions)
  { id: 31, text: "Choose the word most similar to 'Eloquent':", category: "Verbal Ability", options: ["Articulate", "Silent", "Confused", "Boring"], correctAnswer: "Articulate" },
  { id: 32, text: "What is the antonym of 'Benevolent'?", category: "Verbal Ability", options: ["Kind", "Malevolent", "Generous", "Helpful"], correctAnswer: "Malevolent" },
  { id: 33, text: "Complete the sentence: She was _____ by the unexpected news.", category: "Verbal Ability", options: ["astounded", "astound", "astounding", "astounds"], correctAnswer: "astounded" },
  { id: 34, text: "Which word is spelled correctly?", category: "Verbal Ability", options: ["Accomodate", "Accommodate", "Acommodate", "Acomodate"], correctAnswer: "Accommodate" },
  { id: 35, text: "Choose the correct meaning of 'Ubiquitous':", category: "Verbal Ability", options: ["Rare", "Everywhere", "Ancient", "Modern"], correctAnswer: "Everywhere" },
  { id: 36, text: "Identify the error: 'Neither of the students have completed their homework.'", category: "Verbal Ability", options: ["Neither", "have", "their", "No error"], correctAnswer: "have" },
  { id: 37, text: "What is a synonym for 'Meticulous'?", category: "Verbal Ability", options: ["Careless", "Careful", "Quick", "Lazy"], correctAnswer: "Careful" },
  { id: 38, text: "Choose the best word to complete: The evidence was _____ and could not be disputed.", category: "Verbal Ability", options: ["ambiguous", "irrefutable", "questionable", "dubious"], correctAnswer: "irrefutable" },
  { id: 39, text: "What does 'Ephemeral' mean?", category: "Verbal Ability", options: ["Lasting", "Temporary", "Eternal", "Strong"], correctAnswer: "Temporary" },
  { id: 40, text: "Which sentence is grammatically correct?", category: "Verbal Ability", options: ["She don't like coffee", "She doesn't likes coffee", "She doesn't like coffee", "She not like coffee"], correctAnswer: "She doesn't like coffee" },
  { id: 41, text: "Choose the word that best fits: His _____ nature made him popular among friends.", category: "Verbal Ability", options: ["gregarious", "reclusive", "hostile", "timid"], correctAnswer: "gregarious" },
  { id: 42, text: "What is the opposite of 'Verbose'?", category: "Verbal Ability", options: ["Talkative", "Concise", "Lengthy", "Detailed"], correctAnswer: "Concise" },
  { id: 43, text: "Identify the figure of speech: 'The classroom was a zoo.'", category: "Verbal Ability", options: ["Simile", "Metaphor", "Personification", "Hyperbole"], correctAnswer: "Metaphor" },
  { id: 44, text: "Choose the correct form: 'Between you and _____, I think he's wrong.'", category: "Verbal Ability", options: ["I", "me", "myself", "mine"], correctAnswer: "me" },
  { id: 45, text: "What does 'Pragmatic' mean?", category: "Verbal Ability", options: ["Idealistic", "Practical", "Theoretical", "Imaginative"], correctAnswer: "Practical" },
  { id: 46, text: "Which word is a synonym for 'Candid'?", category: "Verbal Ability", options: ["Dishonest", "Frank", "Secretive", "Deceptive"], correctAnswer: "Frank" },
  { id: 47, text: "Complete the idiom: 'A blessing in _____'", category: "Verbal Ability", options: ["disguise", "time", "need", "heaven"], correctAnswer: "disguise" },
  { id: 48, text: "What is the meaning of 'Ambiguous'?", category: "Verbal Ability", options: ["Clear", "Uncertain", "Definite", "Obvious"], correctAnswer: "Uncertain" },
  { id: 49, text: "Choose the correct sentence:", category: "Verbal Ability", options: ["The team are playing well", "The team is playing well", "The team were playing well", "The team be playing well"], correctAnswer: "The team is playing well" },
  { id: 50, text: "What does 'Altruistic' mean?", category: "Verbal Ability", options: ["Selfish", "Selfless", "Greedy", "Ambitious"], correctAnswer: "Selfless" },
  { id: 51, text: "Identify the part of speech of the underlined word: 'She runs quickly.'", category: "Verbal Ability", options: ["Noun", "Verb", "Adjective", "Adverb"], correctAnswer: "Adverb" },
  { id: 52, text: "What is an antonym for 'Diligent'?", category: "Verbal Ability", options: ["Hardworking", "Lazy", "Careful", "Thorough"], correctAnswer: "Lazy" },
  { id: 53, text: "Choose the word that means 'to make worse':", category: "Verbal Ability", options: ["Ameliorate", "Exacerbate", "Improve", "Enhance"], correctAnswer: "Exacerbate" },
  { id: 54, text: "What does 'Nostalgia' mean?", category: "Verbal Ability", options: ["Future thinking", "Longing for the past", "Present focus", "Fear of change"], correctAnswer: "Longing for the past" },
  { id: 55, text: "Which is the correct plural form of 'Crisis'?", category: "Verbal Ability", options: ["Crisises", "Crisis", "Crises", "Crisies"], correctAnswer: "Crises" },
  { id: 56, text: "What is a synonym for 'Resilient'?", category: "Verbal Ability", options: ["Weak", "Flexible", "Rigid", "Fragile"], correctAnswer: "Flexible" },
  { id: 57, text: "Complete: 'Actions speak louder than _____'", category: "Verbal Ability", options: ["words", "deeds", "thoughts", "promises"], correctAnswer: "words" },
  { id: 58, text: "What does 'Juxtapose' mean?", category: "Verbal Ability", options: ["Separate", "Place side by side", "Combine", "Oppose"], correctAnswer: "Place side by side" },
  { id: 59, text: "Choose the correct usage: 'The effect/affect of the medicine was immediate.'", category: "Verbal Ability", options: ["effect", "affect", "both", "neither"], correctAnswer: "effect" },
  { id: 60, text: "What is the meaning of 'Serendipity'?", category: "Verbal Ability", options: ["Bad luck", "Happy accident", "Planned event", "Misfortune"], correctAnswer: "Happy accident" },

  // Numerical Ability (30 questions)
  { id: 61, text: "What is 15% of 200?", category: "Numerical Ability", options: ["20", "25", "30", "35"], correctAnswer: "30" },
  { id: 62, text: "If a shirt costs $40 after a 20% discount, what was the original price?", category: "Numerical Ability", options: ["$48", "$50", "$52", "$60"], correctAnswer: "$50" },
  { id: 63, text: "What is the average of 12, 15, 18, and 21?", category: "Numerical Ability", options: ["15", "16", "16.5", "17"], correctAnswer: "16.5" },
  { id: 64, text: "If x + 5 = 12, what is x?", category: "Numerical Ability", options: ["5", "6", "7", "8"], correctAnswer: "7" },
  { id: 65, text: "What is 3/4 expressed as a percentage?", category: "Numerical Ability", options: ["65%", "70%", "75%", "80%"], correctAnswer: "75%" },
  { id: 66, text: "A train travels 120 km in 2 hours. What is its average speed?", category: "Numerical Ability", options: ["50 km/h", "60 km/h", "70 km/h", "80 km/h"], correctAnswer: "60 km/h" },
  { id: 67, text: "What is the area of a rectangle with length 8 cm and width 5 cm?", category: "Numerical Ability", options: ["13 cm²", "26 cm²", "40 cm²", "80 cm²"], correctAnswer: "40 cm²" },
  { id: 68, text: "If 2x = 16, what is x?", category: "Numerical Ability", options: ["4", "6", "8", "10"], correctAnswer: "8" },
  { id: 69, text: "What is 25% of 80?", category: "Numerical Ability", options: ["15", "20", "25", "30"], correctAnswer: "20" },
  { id: 70, text: "A product costs $150. After a 10% increase, what is the new price?", category: "Numerical Ability", options: ["$160", "$165", "$170", "$175"], correctAnswer: "$165" },
  { id: 71, text: "What is the perimeter of a square with side length 6 cm?", category: "Numerical Ability", options: ["12 cm", "18 cm", "24 cm", "36 cm"], correctAnswer: "24 cm" },
  { id: 72, text: "If 5x - 3 = 17, what is x?", category: "Numerical Ability", options: ["2", "3", "4", "5"], correctAnswer: "4" },
  { id: 73, text: "What is 0.6 expressed as a fraction?", category: "Numerical Ability", options: ["1/2", "3/5", "2/3", "3/4"], correctAnswer: "3/5" },
  { id: 74, text: "A car travels 300 km using 20 liters of fuel. What is the fuel efficiency?", category: "Numerical Ability", options: ["10 km/L", "12 km/L", "15 km/L", "20 km/L"], correctAnswer: "15 km/L" },
  { id: 75, text: "What is the sum of angles in a triangle?", category: "Numerical Ability", options: ["90°", "180°", "270°", "360°"], correctAnswer: "180°" },
  { id: 76, text: "If a = 3 and b = 4, what is a² + b²?", category: "Numerical Ability", options: ["7", "12", "25", "49"], correctAnswer: "25" },
  { id: 77, text: "What is 40% of 250?", category: "Numerical Ability", options: ["80", "90", "100", "110"], correctAnswer: "100" },
  { id: 78, text: "A circle has a radius of 7 cm. What is its diameter?", category: "Numerical Ability", options: ["7 cm", "14 cm", "21 cm", "28 cm"], correctAnswer: "14 cm" },
  { id: 79, text: "If 3x + 2 = 14, what is x?", category: "Numerical Ability", options: ["2", "3", "4", "5"], correctAnswer: "4" },
  { id: 80, text: "What is 1/5 expressed as a decimal?", category: "Numerical Ability", options: ["0.1", "0.2", "0.25", "0.5"], correctAnswer: "0.2" },
  { id: 81, text: "A book costs $25. If you buy 3 books, what is the total cost?", category: "Numerical Ability", options: ["$50", "$65", "$75", "$100"], correctAnswer: "$75" },
  { id: 82, text: "What is the square root of 144?", category: "Numerical Ability", options: ["10", "11", "12", "13"], correctAnswer: "12" },
  { id: 83, text: "If y = 2x and x = 5, what is y?", category: "Numerical Ability", options: ["5", "7", "10", "15"], correctAnswer: "10" },
  { id: 84, text: "What is 60% of 150?", category: "Numerical Ability", options: ["80", "85", "90", "95"], correctAnswer: "90" },
  { id: 85, text: "A rectangle has an area of 48 cm² and width of 6 cm. What is its length?", category: "Numerical Ability", options: ["6 cm", "7 cm", "8 cm", "9 cm"], correctAnswer: "8 cm" },
  { id: 86, text: "If 4x = 28, what is x?", category: "Numerical Ability", options: ["5", "6", "7", "8"], correctAnswer: "7" },
  { id: 87, text: "What is 2/3 of 90?", category: "Numerical Ability", options: ["50", "55", "60", "65"], correctAnswer: "60" },
  { id: 88, text: "A triangle has sides of 3 cm, 4 cm, and 5 cm. What type of triangle is it?", category: "Numerical Ability", options: ["Equilateral", "Isosceles", "Right", "Obtuse"], correctAnswer: "Right" },
  { id: 89, text: "If x/2 = 9, what is x?", category: "Numerical Ability", options: ["12", "14", "16", "18"], correctAnswer: "18" },
  { id: 90, text: "What is 35% of 200?", category: "Numerical Ability", options: ["60", "65", "70", "75"], correctAnswer: "70" },

  // Spatial Reasoning (20 questions)
  { id: 91, text: "How many faces does a cube have?", category: "Spatial Reasoning", options: ["4", "6", "8", "12"], correctAnswer: "6" },
  { id: 92, text: "If you fold a square paper in half twice, how many layers do you have?", category: "Spatial Reasoning", options: ["2", "3", "4", "8"], correctAnswer: "4" },
  { id: 93, text: "Which 3D shape has no vertices?", category: "Spatial Reasoning", options: ["Cube", "Sphere", "Pyramid", "Cone"], correctAnswer: "Sphere" },
  { id: 94, text: "How many edges does a rectangular prism have?", category: "Spatial Reasoning", options: ["8", "10", "12", "14"], correctAnswer: "12" },
  { id: 95, text: "If you rotate a square 90 degrees, what shape do you get?", category: "Spatial Reasoning", options: ["Rectangle", "Square", "Triangle", "Circle"], correctAnswer: "Square" },
  { id: 96, text: "How many corners does a triangle have?", category: "Spatial Reasoning", options: ["2", "3", "4", "5"], correctAnswer: "3" },
  { id: 97, text: "Which shape has the most sides: Pentagon, Hexagon, or Octagon?", category: "Spatial Reasoning", options: ["Pentagon", "Hexagon", "Octagon", "All equal"], correctAnswer: "Octagon" },
  { id: 98, text: "If you cut a cylinder horizontally, what shape is the cross-section?", category: "Spatial Reasoning", options: ["Square", "Circle", "Rectangle", "Triangle"], correctAnswer: "Circle" },
  { id: 99, text: "How many vertices does a pyramid with a square base have?", category: "Spatial Reasoning", options: ["4", "5", "6", "8"], correctAnswer: "5" },
  { id: 100, text: "Which shape can be folded to make a cube?", category: "Spatial Reasoning", options: ["Cross shape with 6 squares", "Circle", "Triangle", "Pentagon"], correctAnswer: "Cross shape with 6 squares" },
  { id: 101, text: "If you look at a cone from above, what shape do you see?", category: "Spatial Reasoning", options: ["Triangle", "Circle", "Square", "Rectangle"], correctAnswer: "Circle" },
  { id: 102, text: "How many faces does a triangular prism have?", category: "Spatial Reasoning", options: ["3", "4", "5", "6"], correctAnswer: "5" },
  { id: 103, text: "Which 3D shape is formed by rotating a rectangle around one of its sides?", category: "Spatial Reasoning", options: ["Sphere", "Cylinder", "Cone", "Cube"], correctAnswer: "Cylinder" },
  { id: 104, text: "How many lines of symmetry does a square have?", category: "Spatial Reasoning", options: ["2", "4", "6", "8"], correctAnswer: "4" },
  { id: 105, text: "If you unfold a cube, how many squares do you see?", category: "Spatial Reasoning", options: ["4", "5", "6", "8"], correctAnswer: "6" },
  { id: 106, text: "Which shape has no straight edges?", category: "Spatial Reasoning", options: ["Square", "Triangle", "Circle", "Pentagon"], correctAnswer: "Circle" },
  { id: 107, text: "How many vertices does a hexagon have?", category: "Spatial Reasoning", options: ["4", "5", "6", "8"], correctAnswer: "6" },
  { id: 108, text: "If you slice a sphere in half, what shape is the cross-section?", category: "Spatial Reasoning", options: ["Square", "Circle", "Triangle", "Rectangle"], correctAnswer: "Circle" },
  { id: 109, text: "Which shape has exactly 4 right angles?", category: "Spatial Reasoning", options: ["Triangle", "Pentagon", "Rectangle", "Hexagon"], correctAnswer: "Rectangle" },
  { id: 110, text: "How many edges does a tetrahedron have?", category: "Spatial Reasoning", options: ["4", "6", "8", "12"], correctAnswer: "6" },

  // Problem Solving (20 questions)
  { id: 111, text: "You have a 3-liter jug and a 5-liter jug. How can you measure exactly 4 liters?", category: "Problem Solving", options: ["Fill 5L, pour into 3L, empty 3L, pour remaining 2L into 3L, fill 5L again, pour into 3L until full", "Fill both jugs", "Use only the 5L jug", "Cannot be done"], correctAnswer: "Fill 5L, pour into 3L, empty 3L, pour remaining 2L into 3L, fill 5L again, pour into 3L until full" },
  { id: 112, text: "A farmer has 17 sheep. All but 9 die. How many are left?", category: "Problem Solving", options: ["8", "9", "17", "0"], correctAnswer: "9" },
  { id: 113, text: "You're in a race and overtake the person in second place. What position are you in?", category: "Problem Solving", options: ["First", "Second", "Third", "Fourth"], correctAnswer: "Second" },
  { id: 114, text: "A bat and ball cost $1.10. The bat costs $1 more than the ball. How much does the ball cost?", category: "Problem Solving", options: ["$0.05", "$0.10", "$0.15", "$0.20"], correctAnswer: "$0.05" },
  { id: 115, text: "If you have 3 apples and take away 2, how many apples do you have?", category: "Problem Solving", options: ["1", "2", "3", "5"], correctAnswer: "2" },
  { id: 116, text: "A clock shows 3:15. What is the angle between the hour and minute hands?", category: "Problem Solving", options: ["0°", "7.5°", "15°", "30°"], correctAnswer: "7.5°" },
  { id: 117, text: "You have 12 coins, one of which is counterfeit and lighter. Using a balance scale only 3 times, how do you find it?", category: "Problem Solving", options: ["Divide into groups of 4, weigh two groups, then subdivide", "Weigh all at once", "Weigh one by one", "Cannot be done in 3 weighings"], correctAnswer: "Divide into groups of 4, weigh two groups, then subdivide" },
  { id: 118, text: "A snail climbs 3 feet up a wall each day but slides down 2 feet each night. How many days to reach the top of a 10-foot wall?", category: "Problem Solving", options: ["7 days", "8 days", "9 days", "10 days"], correctAnswer: "8 days" },
  { id: 119, text: "You have two ropes that each take exactly 60 minutes to burn. How can you measure 45 minutes?", category: "Problem Solving", options: ["Light one rope at both ends and the other at one end simultaneously", "Light one rope only", "Cut the ropes", "Cannot be done"], correctAnswer: "Light one rope at both ends and the other at one end simultaneously" },
  { id: 120, text: "A man builds a house with all four sides facing south. A bear walks by. What color is the bear?", category: "Problem Solving", options: ["Brown", "Black", "White", "Cannot determine"], correctAnswer: "White" },
  { id: 121, text: "You're running a race and pass the person in last place. What position are you in?", category: "Problem Solving", options: ["Last", "Second to last", "First", "Impossible scenario"], correctAnswer: "Impossible scenario" },
  { id: 122, text: "A bottle and cork cost $1.10. The bottle costs $1 more than the cork. How much does the bottle cost?", category: "Problem Solving", options: ["$1.00", "$1.05", "$1.10", "$1.15"], correctAnswer: "$1.05" },
  { id: 123, text: "If 5 cats catch 5 mice in 5 minutes, how many cats catch 100 mice in 100 minutes?", category: "Problem Solving", options: ["5", "20", "100", "500"], correctAnswer: "5" },
  { id: 124, text: "A lily pad doubles in size every day. If it takes 48 days to cover a pond, when is the pond half covered?", category: "Problem Solving", options: ["Day 24", "Day 40", "Day 47", "Day 48"], correctAnswer: "Day 47" },
  { id: 125, text: "You have 9 balls, one heavier than the rest. Using a balance scale twice, how do you find it?", category: "Problem Solving", options: ["Divide into groups of 3, weigh two groups, then subdivide", "Weigh all at once", "Weigh one by one", "Cannot be done in 2 weighings"], correctAnswer: "Divide into groups of 3, weigh two groups, then subdivide" },
  { id: 126, text: "A man has to cross a river with a fox, chicken, and grain. The boat can only carry him and one item. How does he do it?", category: "Problem Solving", options: ["Take chicken first, return, take fox, bring chicken back, take grain, return for chicken", "Take fox first", "Take grain first", "Cannot be done"], correctAnswer: "Take chicken first, return, take fox, bring chicken back, take grain, return for chicken" },
  { id: 127, text: "If it takes 10 workers 10 days to build a wall, how long does it take 5 workers?", category: "Problem Solving", options: ["5 days", "10 days", "15 days", "20 days"], correctAnswer: "20 days" },
  { id: 128, text: "You have 100 doors, all closed. You make 100 passes. On pass n, you toggle every nth door. How many doors are open after 100 passes?", category: "Problem Solving", options: ["10", "25", "50", "100"], correctAnswer: "10" },
  { id: 129, text: "A car travels from A to B at 40 km/h and returns at 60 km/h. What is the average speed?", category: "Problem Solving", options: ["48 km/h", "50 km/h", "52 km/h", "55 km/h"], correctAnswer: "48 km/h" },
  { id: 130, text: "You have 3 switches outside a room with 3 bulbs inside. You can only enter once. How do you determine which switch controls which bulb?", category: "Problem Solving", options: ["Turn on switch 1 for 5 minutes, turn off, turn on switch 2, enter room", "Turn on all switches", "Enter multiple times", "Cannot be done"], correctAnswer: "Turn on switch 1 for 5 minutes, turn off, turn on switch 2, enter room" },

  // Interest & Personality (20 questions)
  { id: 131, text: "I prefer working with people rather than working alone.", category: "Interest & Personality", options: ["Strongly Agree", "Agree", "Neutral", "Disagree"], correctAnswer: "Strongly Agree" },
  { id: 132, text: "I enjoy solving complex mathematical problems.", category: "Interest & Personality", options: ["Strongly Agree", "Agree", "Neutral", "Disagree"], correctAnswer: "Strongly Agree" },
  { id: 133, text: "I am comfortable speaking in front of large groups.", category: "Interest & Personality", options: ["Strongly Agree", "Agree", "Neutral", "Disagree"], correctAnswer: "Strongly Agree" },
  { id: 134, text: "I prefer structured tasks with clear guidelines.", category: "Interest & Personality", options: ["Strongly Agree", "Agree", "Neutral", "Disagree"], correctAnswer: "Strongly Agree" },
  { id: 135, text: "I enjoy creative activities like art or music.", category: "Interest & Personality", options: ["Strongly Agree", "Agree", "Neutral", "Disagree"], correctAnswer: "Strongly Agree" },
  { id: 136, text: "I am interested in understanding how things work mechanically.", category: "Interest & Personality", options: ["Strongly Agree", "Agree", "Neutral", "Disagree"], correctAnswer: "Strongly Agree" },
  { id: 137, text: "I like helping others solve their problems.", category: "Interest & Personality", options: ["Strongly Agree", "Agree", "Neutral", "Disagree"], correctAnswer: "Strongly Agree" },
  { id: 138, text: "I prefer outdoor activities to indoor activities.", category: "Interest & Personality", options: ["Strongly Agree", "Agree", "Neutral", "Disagree"], correctAnswer: "Strongly Agree" },
  { id: 139, text: "I enjoy reading and learning about new topics.", category: "Interest & Personality", options: ["Strongly Agree", "Agree", "Neutral", "Disagree"], correctAnswer: "Strongly Agree" },
  { id: 140, text: "I am good at persuading others to see my point of view.", category: "Interest & Personality", options: ["Strongly Agree", "Agree", "Neutral", "Disagree"], correctAnswer: "Strongly Agree" },
  { id: 141, text: "I prefer working on long-term projects rather than short tasks.", category: "Interest & Personality", options: ["Strongly Agree", "Agree", "Neutral", "Disagree"], correctAnswer: "Strongly Agree" },
  { id: 142, text: "I enjoy analyzing data and finding patterns.", category: "Interest & Personality", options: ["Strongly Agree", "Agree", "Neutral", "Disagree"], correctAnswer: "Strongly Agree" },
  { id: 143, text: "I am interested in social issues and community service.", category: "Interest & Personality", options: ["Strongly Agree", "Agree", "Neutral", "Disagree"], correctAnswer: "Strongly Agree" },
  { id: 144, text: "I like working with my hands and building things.", category: "Interest & Personality", options: ["Strongly Agree", "Agree", "Neutral", "Disagree"], correctAnswer: "Strongly Agree" },
  { id: 145, text: "I am comfortable with ambiguity and uncertainty.", category: "Interest & Personality", options: ["Strongly Agree", "Agree", "Neutral", "Disagree"], correctAnswer: "Strongly Agree" },
  { id: 146, text: "I enjoy leading teams and taking charge of projects.", category: "Interest & Personality", options: ["Strongly Agree", "Agree", "Neutral", "Disagree"], correctAnswer: "Strongly Agree" },
  { id: 147, text: "I prefer routine and predictability in my work.", category: "Interest & Personality", options: ["Strongly Agree", "Agree", "Neutral", "Disagree"], correctAnswer: "Strongly Agree" },
  { id: 148, text: "I am interested in scientific research and experimentation.", category: "Interest & Personality", options: ["Strongly Agree", "Agree", "Neutral", "Disagree"], correctAnswer: "Strongly Agree" },
  { id: 149, text: "I enjoy writing and expressing ideas through words.", category: "Interest & Personality", options: ["Strongly Agree", "Agree", "Neutral", "Disagree"], correctAnswer: "Strongly Agree" },
  { id: 150, text: "I am motivated by financial success and career advancement.", category: "Interest & Personality", options: ["Strongly Agree", "Agree", "Neutral", "Disagree"], correctAnswer: "Strongly Agree" },
];
