/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Response = IDL.Record({
  'isCorrect' : IDL.Bool,
  'answer' : IDL.Text,
  'questionId' : IDL.Nat,
});
export const AssessmentSession = IDL.Record({
  'startTime' : Time,
  'responses' : IDL.Vec(Response),
  'completed' : IDL.Bool,
  'student' : IDL.Principal,
  'sessionId' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'school' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const CareerReport = IDL.Record({
  'content' : IDL.Text,
  'updatedTime' : Time,
  'assessmentSessionId' : IDL.Text,
  'version' : IDL.Nat,
  'student' : IDL.Principal,
  'reportId' : IDL.Text,
  'generatedTime' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeAssessmentSession' : IDL.Func([IDL.Text], [], []),
  'createCareerReport' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAssessmentSession' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AssessmentSession)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCareerReport' : IDL.Func([IDL.Text], [IDL.Opt(CareerReport)], ['query']),
  'getUserAssessmentSessions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(AssessmentSession)],
      ['query'],
    ),
  'getUserCareerReports' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(CareerReport)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startAssessmentSession' : IDL.Func([IDL.Text], [], []),
  'submitResponse' : IDL.Func([IDL.Text, Response], [], []),
  'updateCareerReport' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Response = IDL.Record({
    'isCorrect' : IDL.Bool,
    'answer' : IDL.Text,
    'questionId' : IDL.Nat,
  });
  const AssessmentSession = IDL.Record({
    'startTime' : Time,
    'responses' : IDL.Vec(Response),
    'completed' : IDL.Bool,
    'student' : IDL.Principal,
    'sessionId' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'school' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  const CareerReport = IDL.Record({
    'content' : IDL.Text,
    'updatedTime' : Time,
    'assessmentSessionId' : IDL.Text,
    'version' : IDL.Nat,
    'student' : IDL.Principal,
    'reportId' : IDL.Text,
    'generatedTime' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeAssessmentSession' : IDL.Func([IDL.Text], [], []),
    'createCareerReport' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAssessmentSession' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AssessmentSession)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCareerReport' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CareerReport)],
        ['query'],
      ),
    'getUserAssessmentSessions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(AssessmentSession)],
        ['query'],
      ),
    'getUserCareerReports' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(CareerReport)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startAssessmentSession' : IDL.Func([IDL.Text], [], []),
    'submitResponse' : IDL.Func([IDL.Text, Response], [], []),
    'updateCareerReport' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };