/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AssessmentSession {
  'startTime' : Time,
  'responses' : Array<Response>,
  'completed' : boolean,
  'student' : Principal,
  'sessionId' : string,
}
export interface CareerReport {
  'content' : string,
  'updatedTime' : Time,
  'assessmentSessionId' : string,
  'version' : bigint,
  'student' : Principal,
  'reportId' : string,
  'generatedTime' : Time,
}
export interface Response {
  'isCorrect' : boolean,
  'answer' : string,
  'questionId' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'school' : string,
  'name' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeAssessmentSession' : ActorMethod<[string], undefined>,
  'createCareerReport' : ActorMethod<[string, string, string], undefined>,
  'getAssessmentSession' : ActorMethod<[string], [] | [AssessmentSession]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCareerReport' : ActorMethod<[string], [] | [CareerReport]>,
  'getUserAssessmentSessions' : ActorMethod<
    [Principal],
    Array<AssessmentSession>
  >,
  'getUserCareerReports' : ActorMethod<[Principal], Array<CareerReport>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startAssessmentSession' : ActorMethod<[string], undefined>,
  'submitResponse' : ActorMethod<[string, Response], undefined>,
  'updateCareerReport' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];